series:
title: Stack Using Array         
author:
    name: Lakshminarayanan Vijayaraghavan
    email: lv1018@rit.edu
    github: IGME-RIT    
description: Create a stack using an array
language: C++
tags:           
    - Data Structures
extra_resources:
connections:    
