title: Stack Using Array         
author:
    name: Lakshminarayanan Vijayaraghavan
    email: lv1018@rit.edu
    github: IGME-RIT    
description: Create a stack using an array
language: C++
image:
    icon:       
    banner:     
tags:           
    - C++
    - Data Structures
extra_resources:
    - 
connections:    
    -     
